version: "2"

services:
  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: apachekafka
    hostname: kafkaserver
    networks:
      - kafkanet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092
      JMX_PORT: 9999
  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
    networks:
      - kafkanet
    ports:
      - 9000:9000
    links:
      - kafkaserver
    environment:
      ZK_HOSTS: "kafkaserver:2181"
  schema-registry:
    image: "confluentinc/cp-schema-registry" 
    container_name: schemaregistry
    networks:
      - kafkanet
    ports:
      - 8081:8081
    links:
      - kafkaserver
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'kafkaserver:2181'
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
  rest-proxy:
    image: confluent/rest-proxy
    networks:
      - kafkanet
    links:
      - kafkaserver
      - schema-registry
    ports:
      - "8082:8082"
    environment:
      RP_ZOOKEEPER_CONNECT: "kafkaserver:2181"
      RP_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
networks:
  default:
    external:
      name: kafka-shared-net
  kafkanet:
    driver: bridge